# Generated by Django 3.2.5 on 2021-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='default@email.id', max_length=255, unique=True),
        ),
    ]
